server:
  port: 8000
spring :
  application:
    name : nacos-config
  cloud :
    config :
      server:
        git:
          uri: https://github.com/Sorrowisacat/nacosd.git
          serchPaths: springcloud-config	 #远程仓库的文件夹地址
          username: 2874921477@qq.com	 #登录名
          password: hjy040417  #密码
          label: master	         #Git仓库的分支名



